replicaCount: 1

releaseName: final-project

image:
  polyRepository: oferbakria/poly
  polyTag: "2.1"
  yoloRepository: oferbakria/yolo
  yoloTag: "2.1"

polyPort: 8443
yoloPort: 8441


service:
  port: 80

ingress:
  name: ingress-hosts
  host: oferbakria.atech-bot.click
  path: "/"
  tls: tls-secret-oferbakria

imagePullSecrets: dockerhub

maxSurge: 3

