apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.releaseName }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.releaseName }}-polybot
  ports:
    - protocol: TCP
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.polyPort }}